create_kernel:
	python -m ipykernel install --user --name leaflet-choropleth --display-name="Python (Leaflet Choropleth)"

start_notebook:
	jupyter notebook

serve:
	python -m http.server 8001

counties_geojson:
	wget http://eric.clst.org/assets/wiki/uploads/Stuff/gz_2010_us_050_00_500k.json
